name: CD staging

on:
  push:
    branches: [staging]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: cd-staging
  cancel-in-progress: false

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-vercel.yml
    with:
      environment: staging
      vercel-environment: preview
      ref: ${{ github.sha }}
    secrets: inherit
